### PR TITLE
Add missing import of firebase-firestore-script.html to firebase.html

### LINKED ISSUE #285: Firestore: script is not imported in firebase.html
`firebase.html` imports all Firebase scripts provided by polymerfire except firestore. This should be fixed.

### PR DESCRIPTION
**Pull request by merlinnot**
Fixes #285

### CODE REVIEW

**Comment by mbleigh** [comment]
This was intentionally left out since the default always includes the rtdb
elements. In general including both rtdb and firestore is a bad idea as
they each have significant byteweight.

**Comment by merlinnot** [comment]
Ok, closing in favor of https://github.com/firebase/polymerfire/issues/295

**Comment by masonlouchart** [comment]
So, the `firebase-databse-script.html` import shouldn't be removed from the `firebase.html` to left the choice to the user? I'm using `firestore` and don't want use the RTDB. Am I supposed to create my own `firebase.html` file? It's not fair. 😢

**Comment by merlinnot** [comment]
No, you can just import all required files separately, like so:
```html
<link rel="import" href="./cua-imports/firebase/app.html">
<link rel="import" href="./cua-imports/firebase/firestore.html">
<link rel="import" href="./cua-imports/firebase/messaging.html">
```

**Comment by masonlouchart** [comment]
Still not fair.

**Pull request closed without merging**
