### PR TITLE
[WIP] Auto initializeApp when hosted on Firebase

### PR DESCRIPTION
**Pull request by justweb1**
This is a work in progress. It is not quite working yet. This is also probably not the best way to do this so I'm open to any and all constructive feedback.

@mbleigh Please take a look.

Also, sorry I couldn't get the commits to squash.

https://github.com/firebase/polymerfire/issues/221

### CODE REVIEW

**Comment by justweb1** [comment]
I think the issue I'm having is with async. I think I just need to implement an await somewhere. Just trying to understand it to find out where to implement it.

**Comment by mbleigh** [comment]
So I've been thinking about this a little more, and I actually think there's probably a different solution that would be better. There could be a separate file, `firebase-app-auto.html` that, when imported, basically just has:

```js
<link rel="import" href="firebase-app-script.html">
<script src="/__/firebase/init.js"></script>
```

This would perform the same function that the `firebase-app` element does today, but it would eliminate the need to have a `<firebase-app>` element at all for folks who use Firebase Hosting. Instead, they could just do:

```html
<link rel="import" href="polymerfire/firebase-app-auto.html">
```

For this to *actually* be useful, however, it's going to require lazy loading of Firebase modules to work (as mentioned in the other issue). Because right now you'd have to do something like:

```html
<link rel="import" href="polymerfire/firebase-auth.html">
<link rel="import" href="polymerfire/firebase-database.html">
<link rel="import" href="polymerfire/firebase-app-auto.html">
```

Specifically importing them in that order would be necessary, because once `firebase-app-auto` is imported it will initialize the app and subsequent loads won't affect the existing app.

**Comment by justweb1** [comment]
It looked like the lazy loading was almost ready. Do you think these both can be in the next incremental?

**Comment by justweb1** [comment]
Do storage and messaging need to be called before init.js?

**Comment by justweb1** [comment]
There is one other potential issue with calling init.js. The polymer-cli throws an error when building. I reported it here: https://github.com/Polymer/polymer-cli/issues/758

**Comment by justweb1** [comment]
@mbleigh instead of creating another element for auto couldn't we just lazy load with something like this?
https://github.com/justweb1/polymerfire/tree/auto

**Comment by justweb1** [comment]
I'm going to just close this. But I'll leave the issue open.

**Comment by arcodebonte** [comment]
@justweb1 Thanks for your efforts. Did you find a solution to auto-initialize polymerfire yet?

**Comment by justweb1** [comment]
No. I was waiting for an update on the firebase-js SDK to fix lazy loading. It was merged into the main repo and it is probably in polymerfire now. I haven't gone back and checked. Now, just need to test of the domain exists and auto initiate it in firebase-app component.

**Comment by arcodebonte** [comment]
@justweb1 thanks for your fast reply! I got it running with manual adjustment to your proposed code! I hope this commit will be merged soon.

**Comment by justweb1** [comment]
@arcodebonte what is the PR # for this?

**Comment by justweb1** [comment]
@arcodebonte What changes did you make to get it to work? I'm putting together a new PR.

**Comment by arcodebonte** [comment]
I messed your code to let the solution work in my situation. As you can see in the attachment it isn't a neat solution ready for a PR. Hopefully you're able to put together a neat PR.

screenshot 2017-08-21 at 21 56 34

**Pull request closed without merging**
