### PR TITLE
we now have a size attribute reflecting data.length on firebase-query

### PR DESCRIPTION
**Pull request by christophe-g**
Just to be able to bind to the size of the dataset

### CODE REVIEW

**Comment by JosefJezek** [comment]
@mbleigh FYI

**Comment by christophe-g** [comment]
@mbleigh - for your review as well - thanks.

**Comment by tjmonsi** [comment]
would it be best to just use `numChildren()` - https://firebase.google.com/docs/reference/js/firebase.database.DataSnapshot#numChildren

**Comment by merlinnot** [comment]
What’s the reasoning behind this? Why don’t you just use `data.length`?

**Comment by christophe-g** [comment]
@merlinnot - thanks. Old PR, old reasoning (I think I had problems listening to `data.length` in some edge cases).  Closing this PR as not adding any added value.

**Pull request closed without merging**
