### PR TITLE
Added __onFirebaseValue

### PR DESCRIPTION
**Pull request by limhenry**
Please refer to this (https://github.com/firebase/polymerfire/issues/4) for the reason why I add this function.

### CODE REVIEW

**Comment by cdata** [comment]
Hi, thanks for the contribution. I don't think we need to add a test for this, but could you please document the event? Refer to [`iron-ajax`](https://github.com/PolymerElements/iron-ajax/blob/master/iron-ajax.html#L46-L50) documentation for a reference.

**Comment by limhenry** [comment]
@cdata Added Comment for __onFirebaseValue. Please help me check/review is the comment is appropriate or not. Thanks :smile:

**Comment by cdata** [comment]
@limhenry please refer to the link I included in the original comment. There is a special form of documentation for events that should be included. Also, in general we do not add comments to private methods (methods that begin with `__`) unless the implementation is sufficiently esoteric to warrant an explanation.

**Comment by cdata** [comment]
Friendly ping on this PR - updates requested.

**Comment by limhenry** [comment]
TODO: 
 - remove comment from line 288 - 290
 - add comment on line 56:

> ```
> /**
>  * Fired when the query has a new value
>  */
> ```

**Comment by cdata** [comment]
Yes, you are missing the `@event` JSDoc.

`@event firebase-value`. Please refer to the comment I linked to at the beginning of this conversation!

**Comment by mbleigh** [comment]
Actually I'd like to pull the plug on this one. Attaching a value listener should be unnecessary with `firebase-query` and it's going to negatively impact performance. See comments on #4 

Thanks for the PR though, Henry!

**Comment by mgibas** [comment]
Whats the alternative for making app responsive ? ie. how can I show user "no-content" message ? How can I inform user that data is loading (maybe there is no such concept in firebase but in the end of the day request takes some time) ?

**Pull request closed without merging**
